var searchData=
[
  ['choices_0',['Philosophy &amp; design choices',['../index.html#autotoc_md5',1,'']]],
  ['cmake_1',['CMake',['../index.html#autotoc_md10',1,'']]],
  ['concepts_2',['Aggregate-related concepts',['../index.html#autotoc_md16',1,'']]],
  ['concepts_3a_3aaggregate_3',['concepts::aggregate',['../index.html#autotoc_md25',1,'csl::ag::element&lt;std::size_t, concepts::aggregate&gt;'],['../index.html#autotoc_md26',1,'csl::ag::view_element&lt;std::size_t, concepts::aggregate&gt;']]],
  ['configuration_4',['Configuration',['../index.html#autotoc_md11',1,'']]],
  ['content_5',['Content',['../index.html#autotoc_md15',1,'']]],
  ['conversion_6',['Owning conversion',['../index.html#autotoc_md28',1,'']]],
  ['conversion_20for_20aggregate_20types_7',['to-tuple conversion for aggregate types',['../index.html#autotoc_md27',1,'']]],
  ['conversion_20view_20lightweight_20accessor_8',['Non-owning conversion (view, lightweight accessor)',['../index.html#autotoc_md29',1,'']]],
  ['count_9',['Highier limit for aggregate field count',['../index.html#autotoc_md13',1,'']]],
  ['csl_3a_3aag_10',['📦 csl::ag',['../index.html',1,'']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3aaggregate_11',['aggregate',['../conceptcsl_1_1ag_1_1concepts_1_1aggregate.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3aaggregate_5fconstructible_5ffrom_12',['aggregate_constructible_from',['../conceptcsl_1_1ag_1_1concepts_1_1aggregate__constructible__from.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3aaggregate_5fconstructible_5ffrom_5fn_5fvalues_13',['aggregate_constructible_from_n_values',['../conceptcsl_1_1ag_1_1concepts_1_1aggregate__constructible__from__n__values.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3aaggregate_5fdefault_5finitializable_14',['aggregate_default_initializable',['../conceptcsl_1_1ag_1_1concepts_1_1aggregate__default__initializable.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3aconvertible_5fto_15',['convertible_to',['../conceptcsl_1_1ag_1_1concepts_1_1convertible__to.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3aempty_16',['empty',['../conceptcsl_1_1ag_1_1concepts_1_1empty.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3aopt_5fin_5fstd_5ftuple_5finterface_17',['opt_in_std_tuple_interface',['../conceptcsl_1_1ag_1_1concepts_1_1opt__in__std__tuple__interface.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3apair_5flike_18',['pair_like',['../conceptcsl_1_1ag_1_1concepts_1_1pair__like.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3aproduced_19',['produced',['../conceptcsl_1_1ag_1_1concepts_1_1produced.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3astructured_5fbindable_20',['structured_bindable',['../conceptcsl_1_1ag_1_1concepts_1_1structured__bindable.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3astructured_5fbindable_20t_21',['csl::ag::concepts::structured_bindable&lt;T&gt;',['../index.html#autotoc_md22',1,'']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3atuple_5felement_22',['tuple_element',['../conceptcsl_1_1ag_1_1concepts_1_1tuple__element.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3atuple_5flike_23',['tuple_like',['../conceptcsl_1_1ag_1_1concepts_1_1tuple__like.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aconcepts_3a_3aunqualified_5faggregate_24',['unqualified_aggregate',['../conceptcsl_1_1ag_1_1concepts_1_1unqualified__aggregate.html',1,'csl::ag::concepts']]],
  ['csl_3a_3aag_3a_3aelement_20std_3a_3asize_5ft_20concepts_3a_3aaggregate_25',['csl::ag::element&lt;std::size_t, concepts::aggregate&gt;',['../index.html#autotoc_md25',1,'']]],
  ['csl_3a_3aag_3a_3asize_20t_26',['csl::ag::size&lt;T&gt;',['../index.html#autotoc_md24',1,'']]],
  ['csl_3a_3aag_3a_3atuplelike_3a_3aconcepts_3a_3anon_5fstl_5faggregate_27',['non_stl_aggregate',['../conceptcsl_1_1ag_1_1tuplelike_1_1concepts_1_1non__stl__aggregate.html',1,'csl::ag::tuplelike::concepts']]],
  ['csl_3a_3aag_3a_3aview_5felement_20std_3a_3asize_5ft_20concepts_3a_3aaggregate_28',['csl::ag::view_element&lt;std::size_t, concepts::aggregate&gt;',['../index.html#autotoc_md26',1,'']]],
  ['current_20limitations_29',['Current limitations',['../index.html#autotoc_md36',1,'']]]
];
