version: '3.8'

services:
  cpp-toolchain-dev:
    user: vscodeuser
    build:
      context: . # TODO: image with a specific tag
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: 'ubuntu:latest'
        GCC_VERSIONS: '>=13'
        LLVM_VERSIONS: '>=17'
        OPT_IN_INTEGRATE_BAZEL: no
        OPT_IN_INTEGRATE_BUILD2: no
    ports:
      - "2222:22"
    volumes:
      - ..:/workspace
    # git
    command:
      sh -c "git config --global --add safe.directory /workspace"
    # network_mode: host
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
