version: '3.8'

services:
  cpp-toolchain-dev:
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    build:
      context: . # TODO: image with a specific tag
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: 'ubuntu:jammy' # llvm.sh is failing for now on noble (24.04)
        REMOTE_USER_NAME: root
        REMOTE_USER_PASSWORD: 
        GCC_VERSIONS: '>=13'
        LLVM_VERSIONS: '>=17'
        OPT_IN_INTEGRATE_BAZEL: no
        OPT_IN_INTEGRATE_BUILD2: no
      ssh: # requires ssh-agent service running on host
        - default
    ports:
      - "2222:22"
    volumes:
      - ..:/workspace
      - build:/workspace/build/ # build: persistent, yet excluded from mounting
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
volumes:
  build: # build: persistent, yet excluded from mounting
