version: '3.8'

services:
  cpp-toolchain-dev:
    environment:
      - USER_NAME=vscodeuser
    user: ${USER_NAME}
    build:
      context: . # TODO: image with a specific tag
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: 'ubuntu:latest'
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: 'password'
        GCC_VERSIONS: '>=13'
        LLVM_VERSIONS: '>=17'
        OPT_IN_INTEGRATE_BAZEL: no
        OPT_IN_INTEGRATE_BUILD2: no

    ports:
      - "2222:22"
    volumes:
      - ..:/workspace
    # git
    #   WIP: commit as USERNAME in container
    #     ssh-keygen -f '/home/vscodeuser/.ssh/known_hosts' -R 'github.com'
    command:
      sh -c "git config --global --add safe.directory /workspace"
    # network_mode: host
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
