version: '3.8'

services:
  cpp-toolchain-dev:
    # environment:
    #   SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    #   - USER_NAME=vscodeuser
    # user: ${USER_NAME}
    build:
      context: . # TODO: image with a specific tag
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: 'ubuntu:jammy' # llvm.sh is failing for now on noble (24.04)
        REMOTE_USER_NAME: root
        REMOTE_USER_PASSWORD: 
        GCC_VERSIONS: '>=13'
        LLVM_VERSIONS: '>=17'
        OPT_IN_INTEGRATE_BAZEL: no
        OPT_IN_INTEGRATE_BUILD2: no
      ssh: # requires ssh-agent service running on host
        - default
    ports:
      - "2222:22"
    volumes:
      - ..:/workspace
      # - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    # - ./ssh_config:/home/${USER_NAME}/.ssh/config
    # git
    #   WIP: commit as USERNAME in container
    #     ssh-keygen -f '/home/vscodeuser/.ssh/known_hosts' -R 'github.com'
    # command:
    #   sh -c "git config --global --add safe.directory /workspace"
    # network_mode: host
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    #post-create command : gh support - https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
    # curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
