name: clang_build_and_test

on: [push, pull_request]

jobs:
  clang-build_and_test:

    runs-on: ubuntu-24.04 # ubuntu-latest TODO: ${{ matrix.OS }}

    strategy:
        matrix:
            CSL_COMPONENTS: [ ag, ensure, functional, mp, typeinfo, wf ]
            COMPILER:
              - name: llvm
                CMAKE_C_COMPILER: clang
                CMAKE_CXX_COMPILER: clang++
                VERSION: 18
              - name: llvm
                CMAKE_C_COMPILER: clang
                CMAKE_CXX_COMPILER: clang++
                VERSION: 19
              - name: gnu
                CMAKE_C_COMPILER: gcc
                CMAKE_CXX_COMPILER: g++
                VERSION: 13
              - name: gnu
                CMAKE_C_COMPILER: gcc
                CMAKE_CXX_COMPILER: g++
                VERSION: 14
            STL:
              - name: gnu
                CMAKE_CXX_FLAGS: '-stdlib=libstdc++'
              - name: llvm
                CMAKE_CXX_FLAGS: '-stdlib=libc++'
                CMAKE_EXE_LINKER_FLAGS: '-stdlib=libc++ -lc++abi'
            BUILD_TYPE: [ Debug, Release ]
            exclude:
            - COMPILER.name: gnu
              STL.name: llvm

    # WIP: github composite action for build_and_test
    env:
      TOOLCHAIN_PATH: '${{ matrix.BUILD_TYPE }}/${{ matrix.COMPILER.CMAKE_C_COMPILER }}/${{ matrix.STL.name }}/${{ matrix.CSL_COMPONENTS }}'

    steps:
    - uses: actions/checkout@v4

    # TECH-DEBT: only once for all matrix product - one cache per OS, compiler, STL
    # - subaction to build + test a specific cache entry, using a toolchain as argument
    # TODO: cross-build ?
    
    - name: Install compiler (${{matrix.COMPILER.CMAKE_C_COMPILER}}-${{matrix.COMPILER_VERSION}})
      run: |
          sudo apt update -qqy
          chmod +x .devcontainer/scripts/llvm.sh
          sudo ./.devcontainer/scripts/llvm.sh --silent=yes --alias=no --minimalistic --cleanup --versions="${{matrix.COMPILER_VERSION}}"

    - name: CMake create destination directories (${{ env.TOOLCHAIN_PATH }})
      run: |
        cmake -E make_directory ${{github.workspace}}/out/build/${{ env.TOOLCHAIN_PATH }}
        cmake -E make_directory ${{github.workspace}}/out/install/${{ env.TOOLCHAIN_PATH }}
      
    - name: 📦 CMake cache (${{ env.TOOLCHAIN_PATH }})
      run: |
        cmake \
              -DCSL_BUILD_ALL:BOOL=OFF            \
              -DCSL_BENCHMARK_ALL:BOOL=OFF        \
              -DCSL_DOC_ALL:BOOL=OFF              \
              -DCSL_EXAMPLE_ALL:BOOL=OFF          \
              -DCSL_TEST_ALL:BOOL=OFF             \
            \
              -DCSL_BUILD_${{matrix.CSL_COMPONENTS}}:BOOL=TRUE      \
              -DCSL_BENCHMARK_${{matrix.CSL_COMPONENTS}}:BOOL=TRUE  \
              -DCSL_EXAMPLE_${{matrix.CSL_COMPONENTS}}:BOOL=TRUE    \
              -DCSL_EXAMPLE_${{matrix.CSL_COMPONENTS}}:BOOL=TRUE    \
              -DCSL_TEST_${{matrix.CSL_COMPONENTS}}:BOOL=TRUE       \
            \
              -DCMAKE_C_COMPILER=/usr/bin/${{matrix.COMPILER.CMAKE_C_COMPILER}}-${{matrix.COMPILER_VERSION}}                  \
              -DCMAKE_CXX_COMPILER=/usr/bin/${{matrix.COMPILER.CMAKE_CXX_COMPILER}}-${{matrix.COMPILER_VERSION}}              \
              -DCMAKE_CXX_FLAGS="${{matrix.STL.CMAKE_CXX_FLAGS}}"                                              \
              -DCMAKE_BUILD_TYPE:STRING=${{matrix.BUILD_TYPE}}                                                                \
              -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/out/install/${{ env.TOOLCHAIN_PATH }}                         \
              -DCMAKE_GENERATOR:STRING=Ninja                                                                                  \
              -G Ninja                                                                                                        \
              -S ${{github.workspace}}                                                                                        \
              -B ${{github.workspace}}/out/build/${{ env.TOOLCHAIN_PATH }}

    # WIP: build the target, its tests, then use ctest filter to run only the targets tests (or all, as there are the only one which should be builded)
    #   rename tests: test_csl_${{matrix.CSL_COMPONENTS}}_*

    - name: 🏗️ CMake build - (${{ env.TOOLCHAIN_PATH }})
      run: |
        cmake \
            --build ${{github.workspace}}/out/build/${{ env.TOOLCHAIN_PATH }} \
            --config ${{matrix.BUILD_TYPE}} \
            --target all
      # --target ${{matrix.CSL_COMPONENTS}}_build_all_tests

    - name: 🧪 CTest - (${{ env.TOOLCHAIN_PATH }})
      working-directory: ${{github.workspace}}/out/build/${{ env.TOOLCHAIN_PATH }}
      shell: bash
      run: |
        ctest --parallel 10 \
        --output-on-failure \
        --test-dir ${{github.workspace}}/out/build/${{ env.TOOLCHAIN_PATH }}
      # --no-tests=error
      # -R csl_test_${{matrix.CSL_COMPONENTS}}
      # --tests-regex '^csl_test_${{matrix.CSL_COMPONENTS}}*$'

      # TECH-DEBT: check examples (run as tests)
      # TECH-DEBT: check installation

