name: cmake-Ubuntu-clang

on: [push, pull_request]

jobs:
  cmake-Ubuntu-clang_build_test:

    runs-on: ubuntu-24.04 # ubuntu-latest TODO: ${{ matrix.OS }}

    strategy:
        matrix:
            CSL_COMPONENTS: [ag, ensure, functional, mp, typeinfo, wf]
            CLANG_COMPILER_VERSIONS: [17, 18, 19]
            # TODO: compiler with versions as variations, or one file per toolchain (--toolchain <path-to-file>)
            # COMPILER:
            BUILD_TYPE: [Debug, Release]
            STL_IMPLEMENTATION:
              - name: gnu
                cxx_flags: '-stdlib=libstdc++'
              - name: llvm
                cxx_flags: '-stdlib=libc++ -lc++abi'

    env:
      # TODO: one cache per OS, compiler, STL
      PATH_CHUNK: '${{matrix.BUILD_TYPE}}/${{matrix.STL_IMPLEMENTATION.name}}/${{matrix.CSL_COMPONENTS}}'

    steps:
    - uses: actions/checkout@v4

    # TECH-DEBT: only once for all matrix product
    # - subaction to build + test a specific cache entry, using a toolchain as argument
    
    - name: Install compiler (clang)
      run: |
          sudo apt update -qqy
          chmod +x .devcontainer/scripts/llvm.sh
          sudo ./.devcontainer/scripts/llvm.sh --silent=yes --alias=no --minimalistic --cleanup --versions="${{matrix.CLANG_COMPILER_VERSIONS}}"

    - name: CMake create destination directories (${{ env.PATH_CHUNK }})
      run: |
        cmake -E make_directory ${{github.workspace}}/out/build/${{ env.PATH_CHUNK }}
        cmake -E make_directory ${{github.workspace}}/out/install/${{ env.PATH_CHUNK }}
      
    - name: 📦 CMake cache (${{ env.PATH_CHUNK }})
      run: |
        cmake \
              -DCMAKE_BUILD_TYPE="${{matrix.BUILD_TYPE}}" \
            \
              -DCSL_BENCHMARK_ALL:BOOL=OFF        \
              -DCSL_BUILD_ALL:BOOL=OFF            \
              -DCSL_DOC_ALL:BOOL=OFF              \
              -DCSL_ENABLE_ALL_EXAMPLES:BOOL=OFF  \
              -DCSL_ENABLE_ALL_TESTS:BOOL=OFF     \
              -DCSL_EXAMPLE_ALL:BOOL=OFF          \
              -DCSL_INSTALL_ALL:BOOL=OFF          \
              -DCSL_TEST_ALL:BOOL=OFF             \
            \
              -DCSL_BUILD_${{matrix.CSL_COMPONENTS}}:BOOL=TRUE    \
              -DCSL_TEST_${{matrix.CSL_COMPONENTS}}:BOOL=TRUE     \
              -DCSL_EXAMPLE_${{matrix.CSL_COMPONENTS}}:BOOL=TRUE  \
            \
              -DCMAKE_C_COMPILER=/usr/bin/clang-${{matrix.CLANG_COMPILER_VERSIONS}}                                           \
              -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${{matrix.CLANG_COMPILER_VERSIONS}}                                       \
              -DCMAKE_CXX_FLAGS="${{matrix.STL_IMPLEMENTATION.cxx_flags}}"                                                    \
              -DCMAKE_BUILD_TYPE:STRING=${{matrix.BUILD_TYPE}}                                                                \
              -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/out/install/${{ env.PATH_CHUNK }} \
              -S ${{github.workspace}}                                                                                        \
              -B ${{github.workspace}}/out/build/${{ env.PATH_CHUNK }}

    # WIP: build the target, its tests, then use ctest filter to run only the targets tests (or all, as there are the only one which should be builded)
    #   rename tests: test_csl_${{matrix.CSL_COMPONENTS}}_*

    - name: 🏗️ CMake build - (${{ env.PATH_CHUNK }})
      run: |
        cmake \
            --build ${{github.workspace}}/out/build/${{ env.PATH_CHUNK }} \
            --config ${{matrix.BUILD_TYPE}}
      # --target ${{matrix.CSL_COMPONENTS}}_build_all_tests

    - name: 🧪 CTest - (${{ env.PATH_CHUNK }})
      working-directory: ${{github.workspace}}/out/build/${{ env.PATH_CHUNK }}
      shell: bash
      run: ctest # -R csl_test_${{matrix.CSL_COMPONENTS}}

      # TECH-DEBT: check examples (run as tests)
      # TECH-DEBT: check installation
