name: cmake-Ubuntu-clang

on: [push, pull_request]

env:
  release_id: 16
  CC:   clang-16
  CXX:  clang++-16
  gcc_release_id: 13

jobs:
  cmake-Ubuntu-clang_build_test:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            BUILD_TYPE: [Debug, Release]
            STL_IMPLEMENTATION: [libstdc++, libc++ -lc++abi]
            CSL_COMPONENTS: [wf, mp]

    steps:
    - uses: actions/checkout@v2

    - name: Initialize compiler (Clang)
    # sudo add-apt-repository ppa:ubuntu-toolchain-r/test -> latest gcc
      run: |
          sudo apt update
          sudo apt install \
            gcc-$gcc_release_id \
            libstdc++-$gcc_release_id-dev
          wget https://apt.llvm.org/llvm.sh \
            && chmod +x llvm.sh             \
            && sudo ./llvm.sh $release_id all  \
            && rm llvm.sh
          sudo update-alternatives \
            --install /usr/bin/clang clang /usr/bin/clang-$release_id 100
          sudo update-alternatives \
            --install /usr/bin/clang++ clang++ /usr/bin/clang++-$release_id 100
          sudo apt install libc++1-$release_id libc++-$release_id-dev libc++abi-$release_id-dev libc++abi1-$release_id

    - name: cmake create build env - ${{matrix.BUILD_TYPE}} - ${{matrix.STL_IMPLEMENTATION}}
      run: |
        cmake -E make_directory ${{github.workspace}}/out/build/${{matrix.BUILD_TYPE}}/${{matrix.CSL_COMPONENTS}}
        cmake -E make_directory ${{github.workspace}}/out/install/${{matrix.BUILD_TYPE}}/${{matrix.CSL_COMPONENTS}}
      
    - name: cmake cache - ${{matrix.CSL_COMPONENTS}} (${{matrix.BUILD_TYPE}}, ${{matrix.STL_IMPLEMENTATION}})
      run: |
        cmake \
            -DCMAKE_CXX_FLAGS="-stdlib=${{matrix.STL_IMPLEMENTATION}}"                              \
            -DCSL_BUILD_TEST_${{matrix.CSL_COMPONENTS}}:BOOL=TRUE                                   \
            -DCMAKE_BUILD_TYPE:STRING=${{matrix.BUILD_TYPE}}                                        \
            -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/out/install/${{matrix.BUILD_TYPE}}/${{matrix.CSL_COMPONENTS}}    \
            -S ${{github.workspace}}                                                                \
            -B ${{github.workspace}}/out/build/${{matrix.BUILD_TYPE}}/${{matrix.CSL_COMPONENTS}}

    - name: cmake build - ${{matrix.CSL_COMPONENTS}} (${{matrix.BUILD_TYPE}}, ${{matrix.STL_IMPLEMENTATION}})
      run: |
        cmake \
            --build ${{github.workspace}}/out/build/${{matrix.BUILD_TYPE}}/${{matrix.CSL_COMPONENTS}}  \
            --config ${{matrix.BUILD_TYPE}}

    # Tests
    - name: Test - ${{matrix.CSL_COMPONENTS}} (${{matrix.BUILD_TYPE}}, ${{matrix.STL_IMPLEMENTATION}})
      working-directory: ${{github.workspace}}/out/build/${{matrix.BUILD_TYPE}}/${{matrix.CSL_COMPONENTS}}
      shell: bash
      run: ctest -R csl_validate_${{matrix.CSL_COMPONENTS}}
