name: csl integration CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

jobs:
  integration_test:

    name: Integration (${{ matrix.configuration.CMAKE_C_COMPILER }}-${{ matrix.configuration.version }})
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - { CMAKE_C_COMPILER: clang, CMAKE_CXX_COMPILER: clang++, version: 19 }
          - { CMAKE_C_COMPILER: gcc,   CMAKE_CXX_COMPILER: g++,     version: 14 }

    env:
      build_dir: ${{ github.workspace }}/out/integration/${{ matrix.configuration.CMAKE_C_COMPILER }}-${{ matrix.configuration.version }}

    steps:
    - uses: actions/checkout@v4

    - name: Install clang
      if: matrix.configuration.CMAKE_C_COMPILER == 'clang'
      run: |
        sudo apt update -qqy
        script_name="${{ github.workspace }}/.devcontainer/scripts/llvm.sh"
        sudo chmod +x "${script_name}" && sudo "${script_name}" --silent=yes --alias=no --minimalistic --cleanup --versions="${{ matrix.configuration.version }}"

    - name: Install gcc
      if: matrix.configuration.CMAKE_C_COMPILER == 'gcc'
      run: |
        sudo apt update -qqy
        script_name="${{ github.workspace }}/.devcontainer/scripts/gcc.sh"
        sudo chmod +x "${script_name}" && sudo "${script_name}" --silent=yes --alias=no --versions="${{ matrix.configuration.version }}"

    - name: 📦 Configure, build and test
      working-directory: ${{ github.workspace }}/test/integration
      env:
        CMAKE_C_COMPILER:   ${{ matrix.configuration.CMAKE_C_COMPILER }}
        CMAKE_CXX_COMPILER: ${{ matrix.configuration.CMAKE_CXX_COMPILER }}
      run: |
        bash build.sh "${{ env.build_dir }}"  \
          -Dcsl_integration_test_GIT_TAG=${{ github.sha }}
