name: csl CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

jobs:
  build_and_test:

    name: ${{ format('{0} ({1}, {2})', matrix.CSL_component, matrix.configuration.preset, matrix.configuration.version) }}

    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        CSL_component: [ ag, ensure, functional, mp, typeinfo, wf ]
        configuration:
          # clang + libstdc++
          - { preset: clang-libstdcxx, compiler: clang, version: 18            }
          - { preset: clang-libstdcxx, compiler: clang, version: latest-stable }
          # clang + libc++
          - { preset: clang-libcxx,    compiler: clang, version: 18            }
          - { preset: clang-libcxx,    compiler: clang, version: latest-stable }
          # gcc + libstdc++
          - { preset: gcc,             compiler: gcc,   version: 13            }
          - { preset: gcc,             compiler: gcc,   version: latest-stable }

    steps:
    - uses: actions/checkout@v4

    - name: Install clang
      if: matrix.configuration.compiler == 'clang'
      run: |
        sudo apt update -qqy
        script_name="${{ github.workspace }}/.devcontainer/scripts/llvm.sh"
        sudo chmod +x "${script_name}" && sudo "${script_name}" --silent=yes --alias=no --minimalistic --cleanup --versions="${{ matrix.configuration.version }}"

    - name: Install gcc
      if: matrix.configuration.compiler == 'gcc'
      run: |
        sudo apt update -qqy
        script_name="${{ github.workspace }}/.devcontainer/scripts/gcc.sh"
        sudo chmod +x "${script_name}" && sudo "${script_name}" --silent=yes --alias=no --versions="${{ matrix.configuration.version }}"

    - name: 💡 Compiler information
      run: ${{ matrix.configuration.compiler }} --version

    - name: 📦 CMake configure
      run: |
        cmake --preset ${{ matrix.configuration.preset }} \
          -DCSL_BUILD_ALL:BOOL=FALSE     \
          -DCSL_BENCHMARK_ALL:BOOL=FALSE \
          -DCSL_EXAMPLE_ALL:BOOL=FALSE   \
          -DCSL_TEST_ALL:BOOL=FALSE      \
          -DCSL_BUILD_${{ matrix.CSL_component }}:BOOL=TRUE      \
          -DCSL_BENCHMARK_${{ matrix.CSL_component }}:BOOL=TRUE  \
          -DCSL_EXAMPLE_${{ matrix.CSL_component }}:BOOL=TRUE    \
          -DCSL_TEST_${{ matrix.CSL_component }}:BOOL=TRUE

    - name: 🏗️ CMake build (Debug)
      run: cmake --build --preset ${{ matrix.configuration.preset }}-debug

    - name: 🧪 CTest (Debug)
      run: ctest --preset ${{ matrix.configuration.preset }}-debug

    - name: 🏗️ CMake build (Release)
      run: cmake --build --preset ${{ matrix.configuration.preset }}-release

    - name: 🧪 CTest (Release)
      run: ctest --preset ${{ matrix.configuration.preset }}-release

  ci_passed:
    name: CI passed
    needs: build_and_test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check matrix result
        run: |
          if [[ "${{ needs.build_and_test.result }}" != "success" ]]; then
            echo "Matrix jobs failed or were cancelled"
            exit 1
          fi
