name: cmake-Ubuntu-clang

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]
        COMPILER: [gcc, clang]  # This allows you to dynamically choose GCC or Clang
        CLANG_COMPILER_VERSIONS: [17, 18, 19]
        GCC_COMPILER_VERSIONS: [13, 14]
        STL_IMPLEMENTATION: [libstdc++, libc++ -lc++abi]

    steps:
      - name: Set up matrix values
        run: |
          echo "Build Type: ${{ matrix.BUILD_TYPE }}"
          echo "Compiler: ${{ matrix.COMPILER }}"

          # Handle GCC specifics
          if [[ "${{ matrix.COMPILER }}" == "gcc" ]]; then
            echo "Using GCC version: ${{ matrix.GCC_COMPILER_VERSIONS }}"
          fi

          # Handle Clang specifics
          if [[ "${{ matrix.COMPILER }}" == "clang" ]]; then
            echo "Using Clang version: ${{ matrix.CLANG_COMPILER_VERSIONS }}"
            echo "Using STL Implementation: ${{ matrix.STL_IMPLEMENTATION }}"
          fi

