name: documentation

on:
  workflow_run:
    workflows: ["csl consumption CI"]
    types: [completed]

permissions:
  contents: write

jobs:
  build-and-deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -qqy
          sudo apt-get install -y graphviz

      - name: Generate documentation
        run: bash doc/scripts/generate_doc.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: doc/output
